### ISSUE TITLE
URL incorrectly detected in Firefox.

### ISSUE THREAD

**Issue by KnightTim** [anonymous1184/bitwarden-autotype#32] opened 2022-05-16 20:25 UTC
This may be related to the fix for issue #30 

I used to be able to have autotype detect a URI for an extension in FF starting with `moz-extension://`

Now instead of correctly filling the field in for the extension it prompts me to choose from one of my google accounts.  This seems to only happen in firefox windows with a tab pinned, possibly only if you have the tab pinned from a previous session. 

I'm using Firefox 91.7.0esr (64-bit)

**Comment by KnightTim** [comment] 2022-05-17 12:42
I can create another issue for this if you want, but I noticed a quirk of the way sub-releases have been done, there is no way to download an earlier version of a release.  I can't download v1.1.4 or 1.1.4.2.  I would recommend creating a new release for sub versions.

**Comment by anonymous1184** [comment] 2022-05-17 20:19
> This may be related to the fix for issue #30
> I used to be able to have autotype detect a URI for an extension in FF starting with `moz-extension://`

You're completely right, this is a regression.

---

And right again, I should be doing a release per build (as I intended) but the truth is that free time has been hard to come by that's why I didn't.

I now see that no matter how much I try to insists "*this is just scripting*" it needs to be done properly like any other app: it needs a proper branching strategy (perhaps based on feature/hotfix by issue number) and automated release creation (build-based) with artifacts upload.

---

Thanks a lot for the report and the insight.  Code is pushed to master, and the assets were updated (this will be the last update to any released asset).

**Closed by anonymous1184** 2022-05-17 20:19 UTC

**Comment by KnightTim** [comment] 2022-05-18 00:01
Thanks for the quick response. 

This is a project you're doing for the benefit of the community for free, so I hope you don't take things as a complaints. I think this is an awesome tool and don't want you to stop the development, because you feel like you can't make it perfect. 

Thanks again for fixing things and creating this tool.

**Comment by anonymous1184** [comment] 2022-05-20 00:13
I would never took them as complains, *au contraire*. I feel the deepest of the gratitudes because like every other developer I cannot test every single scenario and I'm glad there's someone out there taking the time to point me in the right direction.

And don't worry after 20-something years of working as a programmer I know that not me nor anyone can make anything perfect however exactly that makes everything perfectible... so I once again I thank your for your time so I can get rid of the bugs and keep the gears moving.

Also if I were (never occurred to me) to completely stop working on the project, I would make sure that someone in the lovely AutoHotkey community "*take the mantle*" as this started as a simple script for a friend of mine and now I know for a fact that at very least is used in a couple of not-so-small places were the user base is actually substantial. That gives me the boost to keep going, knowing that there's people like you that find the tool useful.

And no idea is too small or too far fetched, might not align with my vision for the project but until those ideas are not on the table we won't know... so please, never hold on to those. Anything, let me know; I'm glad to hear about new ideas that can be integrated to increase the tool usability.
